# Generated by Django 5.0.1 on 2024-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=45)),
                ('num_doc', models.IntegerField()),
                ('cod_cliente', models.CharField(max_length=45)),
                ('nom_cliente', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('desc_producto', models.TextField()),
                ('total_detalle', models.IntegerField()),
                ('analisis_cn', models.IntegerField()),
                ('comentario', models.TextField()),
                ('linea', models.IntegerField()),
                ('empresa', models.CharField(max_length=45)),
            ],
        ),
    ]
