# Generated by Django 5.0.1 on 2024-02-26 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cene',
            fields=[
                ('id_cene', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^[0-9a-zA-Z]*$')])),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
