# Generated by Django 5.0.1 on 2024-02-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.URLField(null=True)),
                ('file_name', models.CharField(max_length=245, null=True)),
                ('blob_name', models.CharField(default='', max_length=2450)),
                ('tipo', models.CharField(max_length=245, null=True)),
                ('file_extension', models.CharField(max_length=245, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('id_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obras')),
            ],
        ),
    ]
