# Generated by Django 5.0.1 on 2024-02-26 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cene', '0001_initial'),
        ('perfil_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=45)),
                ('cliente', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('presupuesto', models.IntegerField()),
                ('monto_facturado', models.IntegerField(null=True)),
                ('monto_por_facturar', models.IntegerField(null=True)),
                ('porc_avance_financiero', models.IntegerField()),
                ('porc_avance_operativo', models.IntegerField()),
                ('estado_obra', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_asignacion', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=45)),
                ('tipo_obra', models.CharField(max_length=45)),
                ('observaciones', models.TextField(null=True)),
                ('is_gantt', models.BooleanField(default=False)),
                ('is_presupuesto', models.BooleanField(default=False)),
                ('is_avance', models.BooleanField(default=False)),
                ('cene', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cene.cene')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable_obra', to='perfil_usuario.userprofile')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor_obra', to='perfil_usuario.userprofile')),
            ],
            options={
                'ordering': ('empresa', 'cliente', 'responsable', 'nombre', 'presupuesto', 'monto_facturado', 'monto_por_facturar', 'porc_avance_financiero', 'porc_avance_operativo', 'estado_obra', 'fecha_inicio', 'fecha_asignacion', 'supervisor', 'cene', 'direccion', 'comuna', 'tipo_obra', 'observaciones', 'is_gantt', 'is_presupuesto', 'is_avance'),
            },
        ),
    ]
